Road measurements tags
Software-Engineering-2-group-E/LiRA-Map pull request #148
Opened 2022-12-07 20:19 UTC by tbdk

2022-12-07 20:23 UTC, tbdk commented
FIXME: Tags can now be added without the screen going white, but their name value is not saved properly, as they appear as empty tags regardless of whether name is provided or not.

2022-12-09 08:38 UTC, Zarkino requested changes
Man kan lave en measurement type ved kun at give et navn og uden at vælge et tag:
![Measurement Type](https://user-images.githubusercontent.com/31597902/206660303-7c060ac5-b591-45f0-96c4-78f6e6048f3a.png)
![Active](https://user-images.githubusercontent.com/31597902/206660310-e7b2301e-8b11-4eed-ae8a-00416814a3a9.png)

2022-12-09 14:33 UTC, afskylia commented
Virker fint! Hvis du relativt let kan lave validering på at der er et tag, som Fredrik skriver, ville det være nice - ellers tænker jeg vi kan merge det som det er og så finpudse det senere evt.

2022-12-10 15:55 UTC, jonasmittun reviewed
Hvis jeg laver en ny measurement der måler acc.xyz bliver grafen ikke vist, dette burde nogen lige dobbelttjekke inden jeg tør at approve.

2022-12-10 16:01 UTC, jonasmittun approved these changes
Min forrige kommentar kan godt ignoreres, acc.xyz har ikke data for langt de fleste trips hvilket bare ikke vises som en fejl. Når jeg bruger obd.rpm virker det som det skal.

Tror alting virker som det skal, det som frederik kommenterede på er i hvertfald fikset og har ikke fundet andre åbenlyse fejl.

LGTM 🚀

2022-12-10 16:04 UTC, Zarkino approved these changes

2022-12-11 09:20 UTC, merged