Docker migration
Software-Engineering-2-group-E/LiRA-Map pull request #30
Opened 2022-09-18 17:06 UTC by tbdk

2022-09-18 18:50 UTC, mikk5829 requested changes
Vi skal bygge et produktions build, ved npm run build og derefter serve, evt med nodemom. Ellers får brugerne debut beskeder og buildet kører langsomt

2022-09-19 18:08 UTC, tbdk commented
@mikk5829 Tak for feedback! Ved ikke så meget om node js, men vil `--production` flagget ikke gøre at alle dependencies i `devDependencies` i `package.json` ikke bliver downloadet? Vil det ikke være et problem? 

Ved ikke om det giver mening at køre nodemon, indeni i en docker container hvor vi alligevel ikke ændrer dens kode live og har brug for at det bliver re-served? Men der er måske andre fordele? Altså, som det er lige nu, vil serveren være tilgængelig, ligesom vi er vant til :-)

2022-09-19 18:10 UTC, tbdk commented
@mikk5829 Så skulle det selvfølgelig være hvis main får nogle ændringer merged ind, som ikke kræver et rebuild af image, og som blot kan holdes øje med af nodemon og blive re-served. Men hvordan skelner du mellem at ændringerne kræver et rebuild af image, og at det ikke gør, og at nodemon bare kan hente den opdaterede main kode ind? :-)

2022-09-20 06:23 UTC, mikk5829 commented
Lad os kigge på den her: https://mherman.org/blog/dockerizing-a-react-app/

2022-09-20 10:04 UTC, afskylia approved these changes

2022-09-20 10:19 UTC, tbdk commented
Wrong PR closed :D

2022-09-22 14:23 UTC, mikk5829 approved these changes

2022-09-22 14:23 UTC, mikk5829 commented on compose.yaml
> +   - 3000:3000
Burde den ikke udstille port 80? Så slipper brugeren for at skrive :3000 til url

2022-09-23 09:11 UTC, merged